name: Daily Job Pipeline

on:
  schedule:
    # Runs every day at 10 AM UTC AKA 2 AM / 3 AM PST
    - cron: "0 10 * * *"
  workflow_dispatch:  # Allows you to trigger manually

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 180 # 3 hours to ensure everything works

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Run job pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
        run: python -m backend.app.services.run_pipeline